<h1>Calculatrice</h1>

<fieldset>
    <label for="nom">Nombre 1</label>
    <input type="number" name="nb1" id="nb1" />
</fieldset>

<fieldset>
    <label for="nom">Nombre 2</label>
    <input type="number" name="nb2" id="nb2" />
</fieldset>

<fieldset>
    <label for="operation">Opération</label>
    <select name="operation" id="operation">
        <option name="addition" value="addition">+</option>
        <option name="soustraction" value="soustraction">-</option>
        <option name="multiplication" value="multiplication">*</option>
        <option name="division" value="division">/</option>
        <option name="modulo" value="modulo">%</option>
        <option name="power" value="power">puissance</option>
    </select>
</fieldset>

<input type="submit" value="Calculer" />

<h2>Résultat</h2>
