<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Formulaire
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    </head>
    <body id="form">
        <main>
            <form method="post" action="index.php">
                <?php require("calculator.phtml");
                    if (isset($result)) {
                        echo $result;
                    }
                ?>
            </form>
        </main>
    </body>
</html>